config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :features
  resources :items do
    member do
      post :duplicate
    end
  end
  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }
  resources :users

  resource :pages, only: [:index]

  root to: "pages#index"
end

app/views/shared/_flash_message.html.erb
<div class="fixed-bottom">
    <div id="error_explanation">
        <div class="<%= flash_class(alert_type) %> alert-dismissable d-flex justify-content-center">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            <%= msg %>
        </div>
    </div>
</div>

app/views/shared/_navigation.html.haml
%nav.navbar.fixed-top.navbar-expand-lg.navbar-dark.bg-dark.scrolling-navbar
    .container
        .navbar-brand
            Bops IMS
        .navbar-right
            %ul.navbar-nav
                %li.nav-item{ class: "#{active_nav(request_filtered_params, :home)}" }
                    = link_to "Home", root_path, class: 'nav-link'
                - if !user_signed_in?
                    %li.nav-item
                        -# { class: "#{active_nav(request_filtered_params, :login)}" }
                        = link_to "Log In", new_user_session_path, class: 'nav-link'
                    %li.nav-item
                        -# { class: "#{active_nav(request_filtered_params, :signup)}" }
                        = link_to "Sign Up", new_user_registration_path, class: 'nav-link'
                - else
                    %li.nav-item{ class: "#{active_nav(request_filtered_params, :inventory)}" }
                        = link_to "Inventory", items_path, class: 'nav-link'
                    %li.nav-item{ class: "#{active_nav(request_filtered_params, :categories)}" }
                        = link_to "Categories", categories_path, class: 'nav-link'
                    %li.nav-item{ class: "#{active_nav(request_filtered_params, :features)}" }
                        = link_to "Features", features_path, class: 'nav-link'
                    %li.nav-item
                        = link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link text-danger'