config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :features
  resources :items do
    member do
      post :duplicate
    end
  end
  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }
  resources :users

  resource :pages, only: [:index]

  root to: "pages#index"
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :item_features, dependent: :destroy
    has_many :features, through: :item_features

    belongs_to :category
    belongs_to :user

    before_validation { self.name = self.name&.downcase }

    validates :name, presence: true, allow_blank: false
    validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

    def list_of_features
        output_str = ""
        features.each do |feature|
            output_str += feature.title.humanize + ": " + feature.value.humanize
            output_str += ', '
        end
        output_str.chomp(', ')
    end

    def duplicate
        self.dup
    end

    # For scalability and best coding practices, if this were a larger project then I would use a decorator or view_model to provide this method.
    def selected_features
        ItemFeature.where(item_id: self.id, feature_id: Feature.all.collect(&:id)).collect(&:feature_id)
    end

    def price_in_dollars
        self.price / 100.00
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy, :duplicate]
  before_action :set_features, only: [:new, :create, :edit, :update]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item.price = transform_cents_to_dollars(@item.price)
  end

  # POST /items
  # POST /items.json
  def create
    params["item"]["price"] = transform_dollars_to_cents(params["item"]["price"]) if params["item"].present? && params["item"]["price"].present?
    @item = current_user.items.new(item_params)
    item_features_attributes = []
    respond_to do |format|
      if @item.save
        if params['feature_ids'].present?
          params['feature_ids'].each do |feature_id|
            item_features_attributes << ({ item_id: @item.id, feature_id: feature_id.to_i })
          end
          item_features_attributes.each do |i_f_attributes|
            ItemFeature.where(item_id: i_f_attributes[:item_id], feature_id: i_f_attributes[:feature_id]).first_or_create!
          end
        end
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    params["item"]["price"] = transform_dollars_to_cents(params["item"]["price"]) if params["item"].present? && params["item"]["price"].present?
    item_features_attributes = []

    respond_to do |format|
      if @item.update(item_params)
        if params['feature_ids'].present?
          
          params['feature_ids'].each do |feature_id|
            item_features_attributes << ({ item_id: @item.id, feature_id: feature_id.to_i })
          end

          # First or create ItemFeatures for item that are selected
          item_features_attributes.each do |i_f_attributes|
            ItemFeature.where(item_id: i_f_attributes[:item_id], feature_id: i_f_attributes[:feature_id]).first_or_create!
          end

          # Destroy ItemFeatures for item that are not selected
          feature_ids = item_features_attributes.collect{|item_feature| item_feature[:feature_id]}
          ItemFeature.where(item_id: @item.id).where.not(feature_id: feature_ids).destroy_all
        end
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def duplicate
    new_item = @item.duplicate
    feature_ids = @item.features.collect(&:id)
    Item.transaction do
      new_item.save!
      feature_ids.each do |feature_id|
        ItemFeature.create!(item_id: new_item.id, feature_id: feature_id)
      end
    end
    redirect_to items_url, notice: 'Item was successfully duplicated.'
  end

  private
    def set_categories
      @categories = Category.all
    end

    def set_features
      @features = Feature.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:category_id, :name, :amount, :price)
    end

    def transform_dollars_to_cents(price)
      return (price.to_f * 100).to_i.to_s
    end

    def transform_cents_to_dollars(price)
      return sprintf('%.2f', (price.to_f / 100)).to_s
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <%= render partial: "shared/flash_message", locals: { alert_type: 'danger', msg: item.errors.full_messages.to_sentence } %>
  <% end %>

  <div class='form-group'>
    <%= form.label :name %>
    <%= form.text_field :name, value: item.name&.humanize || nil, required: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.select :category_id, options_from_collection_for_select(categories, :id, :title_and_description), {required: true}, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= label_tag "features" %>
    <%= select_tag "feature_ids[]", options_from_collection_for_select(features, :id, :to_s, item.selected_features), {multiple: true, size: 6, class: 'form-control'} %>
  </div>

  <div class='form-group'>
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= form.label :price %>
    <%= form.number_field :price, required: true, step: '.01', class: 'form-control' %>
  </div>

  <div class="actions d-flex align-items-baseline justify-content-between">
    <%= link_to 'Back', items_path, class: 'btn btn-secondary p-2' %>
    <%= form.submit "Submit", class: 'btn btn-primary p-2' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class='container'>
    <div class='d-flex mt-5'>
        <h1>Editing Item</h1>
    </div>

    <%= render 'form', item: @item, features: @features, categories: @categories %>
</div>

app/views/items/index.html.erb
<div class='container'>
  <div class='d-flex mt-5 align-items-center justify-content-between'>
    <h1>Inventory</h1>

    <%= link_to 'New', new_item_path, class: 'btn btn-primary' %>
  </div>

  <div class='d-flex mt-3 justify-content-center filterable'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>ID</th>
          <th scope='col'>Name</th>
          <th scope='col'>Category</th>
          <th scope='col' colspan='2'>Features</th>
          <th scope='col'>Amount</th>
          <th scope='col'>Price</th>
          <th scope='col'>User</th>
          <th scope='col' colspan='2'>Actions</th>
        </tr>
        <tr class='filters'>
          <th><input type='text' class='form-control' placeholder='#'></th>
          <th><input type='text' class='form-control' placeholder='Name'></th>
          <th><input type='text' class='form-control' placeholder='Category'></th>
          <th colspan='2'><input type='text' class='form-control' placeholder='Features'></th>
          <th><input type='text' class='form-control' placeholder='Amount'></th>
          <th><input type='text' class='form-control' placeholder='Price'></th>
          <th><input type='text' class='form-control' placeholder='User'></th>
          <th colspan='2'></th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
          <tr data-attr='inventory'>
            <td><%= item.to_param %></td>
            <td><%= item.name.humanize %></td>
            <td><%= item.category.title.humanize %></td>
            <td colspan='2'><%=  item.list_of_features %></td>
            <td data-value="<%= item.amount %>"><%= item.amount %></td>
            <td data-value="<%= item.price_in_dollars %>"><%= number_to_currency(item.price_in_dollars, precision: 2) %></td>
            <td><%= item.user.email %></td>
            <td colspan='2'>
              <div class='d-flex justify-content-end'>
                <%= link_to "View", item_path(item), class: 'btn btn-primary p-2' %>
                <%= link_to 'Duplicate', duplicate_item_path(item), method: :post, class: 'btn btn-primary p-2 mx-1' %>
                <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger p-2' %>
              </div>
            </td>
          </tr>
        <% end %>
        <tr data-attr='totals'>
          <td scope='row'><strong>Totals:</strong></td>
          <td></td>
          <td></td>
          <td colspan='2'></td>
          <td id='total4' data-value="<%= @items.sum(&:amount) %>"><%= @items.sum(&:amount) %></td>
          <td id='total5' data-value="<%= @items.map{ |item| item.amount * item.price_in_dollars }.sum() %>"><%= number_to_currency(@items.map{ |item| item.amount * item.price_in_dollars }.sum(), precision: 2) %></td>
          <td></td>
          <td colspan='2'></td>
      </tbody>
    </table>
  </div>
</div>

app/views/items/new.html.erb
<div class='container'>
    <div class="d-flex mt-5">
        <h1>New Item</h1>
    </div>

    <%= render 'form', item: @item, features: @features, categories: @categories %>
</div>

app/views/items/show.html.erb
<div class='container'>
  <div class='d-flex flex-column mt-5'>
    <div class='p-2'>
      <p>
        <strong>Name:</strong>
        <%= @item.name.humanize %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>Category:</strong>
        <%= @item.category&.title %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>Feature:</strong>
        <%= @item.list_of_features %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>Amount:</strong>
        <%= @item.amount %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@item.price_in_dollars, precision: 2) %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>User:</strong>
        <%= @item.user.email %>
      </p>
    </div>
  </div>

  <div class='action d-flex align-items-baseline justify-content-between'>
    <%= link_to 'Back', items_path, class: 'btn btn-secondary p-2' %>
    <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary p-2' %>
  </div>
</div>