config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :features
  resources :items do
    member do
      post :duplicate
    end
  end
  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }
  resources :users

  resource :pages, only: [:index]

  root to: "pages#index"
end

app/models/feature.rb
class Feature < ApplicationRecord
    has_many :item_features, dependent: :destroy
    has_many :items, through: :item_features

    belongs_to :user

    before_validation { self.title = self.title&.downcase }
    before_validation { self.value = self.value&.downcase }

    validates :title, presence: true, allow_blank: false
    validates :value, presence: true, allow_blank: false


    def to_s
        "#{title.humanize} - #{value.humanize}"
    end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = current_user.features.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    if @feature.items.any?
      respond_to do |format|
        format.html { redirect_to features_path, alert: 'There are items with this feature and cannot be destroyed.' }
      end
    else
      @feature.destroy
      respond_to do |format|
        format.html { redirect_to features_path, notice: 'Feature was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feature_params
      params.require(:feature).permit(:user_id, :title, :value)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_with(model: feature, local: true) do |form| %>
  <% if feature.errors.any? %>
    <%= render partial: 'shared/flash_message', locals: { alert_type: 'danger', msg: feature.errors.full_messages.to_sentence } %>
  <% end %>

  <div class='row'>
    <div class='col-6'>
      <div class='form-group'>
        <%= form.label :title %>
        <%= form.text_field :title, value: feature.title&.humanize || nil, required: true, class: 'form-control' %>
      </div>
    </div>
    <div class='col-6'>
      <div class='form-group'>
        <%= form.label :value %>
        <%= form.text_field :value, value: feature.value&.humanize || nil, required: true, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="actions d-flex align-items-baseline justify-content-between">
    <%= link_to "Back", features_path, class: 'btn btn-secondary p-2' %>
    <%= form.submit "Submit", class: 'btn btn-primary p-2' %>
  </div>
<% end %>

app/views/features/edit.html.erb
<div class='container'>
    <div class='d-flex mt-5'>
        <h1>Editing Feature</h1>
    </div>

    <%= render 'form', feature: @feature %>
</div>

app/views/features/index.html.erb
<div class='container'>
  <div class='d-flex mt-5 align-items-center justify-content-between'>
    <h1>Features</h1>
    <%= link_to "New", new_feature_path, class: 'btn btn-primary' %>
  </div>
  <div class='d-flex mt-3 justify-content-between'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>ID</th>
          <th scope='col'>Title</th>
          <th scope='col'>Value</th>
          <th scope='col'>User</th>
          <td scope='col'></td>
        </tr>
      </thead>

      <tbody>
        <% @features.each do |feature| %>
          <tr>
            <td><%= feature.to_param %></td>
            <td><%= feature.title&.humanize %>
            <td><%= feature.value&.humanize %>
            <td><%= feature.user.email %>
            <td>
              <div class='d-flex justify-content-end'>
                <%= link_to 'View', feature_path(feature), class: 'btn btn-primary p-2 mr-1' %>
                <%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger p-2' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/features/new.html.erb
<div class='container'>
    <div class='d-flex mt-5'>
        <h1>New Feature</h1>
    </div>

    <%= render 'form', feature: @feature %>
</div>

app/views/features/show.html.erb
<div class='container'>
  <div class='d-flex flex-column mt-5'>
    <div class='p-2'>
      <p>
        <strong>Title:</strong>
        <%= @feature.title&.humanize %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>Value:</strong>
        <%= @feature.value&.humanize %>
      </p>
    </div>
    <div class='p-2'>
      <p>
        <strong>User:</strong>
        <%= @feature.user.email %>
      </p>
    </div>
  </div>

  <div class='actions d-flex align-items-baseline justify-content-between'>
    <%= link_to 'Back', features_path, class: 'btn btn-secondary p-2' %>
    <%= link_to 'Edit', edit_feature_path(@feature), class: 'btn btn-primary p-2' %>
  </div>
</div>